### ISSUE TITLE
After searching, a second caret appears in the results area

### ISSUE THREAD

**Issue by ermau** [bojanrajkovic/GifWin#28] opened 2016-03-10 20:11 UTC
![2016-03-10_15-12-09](https://cloud.githubusercontent.com/assets/156582/13683031/90c0a108-e6d2-11e5-889e-ac91a11b9f78.gif)

**Comment by ermau** [comment] 2016-03-11 03:25
I can't reproduce this in the current source version

**Comment by bojanrajkovic** [comment] 2016-03-11 05:21
I sometimes see this, sometimes don't. I think it's reproducible if you try to add an image _then_ search. The state transitions are probably messed up in the main window.

**Comment by ermau** [comment] 2016-07-29 01:22
Turns out this is actually a bug in the animated caret, it doesn't respect the visibility value of what it's attached to.

**Comment by bojanrajkovic** [comment] 2016-07-29 01:36
Oh! Never would have thought that. There's probably a better way to do the transition so that that's not an issue, but I am not a WPF wizard.





On Thu, Jul 28, 2016 at 9:22 PM -0400, "Eric Maupin" <notifications@github.com<mailto:notifications@github.com>> wrote:


Turns out this is actually a bug in the animated caret, it doesn't respect the visibility value of what it's attached to.

-

**Comment by ermau** [comment] 2017-04-12 22:34
This looks like it's still present or reoccurred in master / current release.

**Comment by bojanrajkovic** [comment] 2017-04-12 22:35
Hmm. Did I unbump the sub module on accident?

**Comment by ermau** [comment] 2017-04-12 22:46
Doesn't look like it, just looks like it wasn't sufficient enough of a fix.

**Comment by bojanrajkovic** [comment] 2017-07-08 01:21
This likely won't be an issue in UWP, so closing.

**Closed by bojanrajkovic** 2017-07-08 01:21 UTC
Labels: bug
